(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(e1) 
		(e2) 
		(e3) 
		(e4) 
		(e5) 
		(e6) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.043 (e2)
				 0.391 (e3)
				 0.348 (e4)
				 0.217 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.000 (e2)
				 0.465 (e3)
				 0.276 (e4)
				 0.259 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.037 (e2)
				 0.259 (e3)
				 0.222 (e4)
				 0.444 (e5)
				 0.037 (e6))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.000 (e2)
				 0.174 (e3)
				 0.290 (e4)
				 0.536 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.069 (e2)
				 0.069 (e3)
				 0.741 (e4)
				 0.086 (e5)
				 0.034 (e6))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.056 (e2)
				 0.083 (e3)
				 0.722 (e4)
				 0.125 (e5)
				 0.014 (e6))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.024 (e2)
				 0.146 (e3)
				 0.610 (e4)
				 0.220 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.000 (e2)
				 0.077 (e3)
				 0.635 (e4)
				 0.288 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.047 (e1)
				 0.023 (e2)
				 0.163 (e3)
				 0.186 (e4)
				 0.325 (e5)
				 0.256 (e6))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.009 (e1)
				 0.000 (e2)
				 0.165 (e3)
				 0.055 (e4)
				 0.394 (e5)
				 0.376 (e6))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.051 (e1)
				 0.058 (e2)
				 0.066 (e3)
				 0.066 (e4)
				 0.212 (e5)
				 0.547 (e6))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.009 (e1)
				 0.000 (e2)
				 0.225 (e3)
				 0.018 (e4)
				 0.243 (e5)
				 0.505 (e6))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.071 (e1)
				 0.000 (e2)
				 0.143 (e3)
				 0.000 (e4)
				 0.071 (e5)
				 0.714 (e6))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.071 (e1)
				 0.000 (e2)
				 0.143 (e3)
				 0.000 (e4)
				 0.071 (e5)
				 0.714 (e6))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.908 (e1)
				 0.013 (e2)
				 0.000 (e3)
				 0.000 (e4)
				 0.013 (e5)
				 0.066 (e6))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.875 (e1)
				 0.021 (e2)
				 0.031 (e3)
				 0.000 (e4)
				 0.021 (e5)
				 0.052 (e6))
				(not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.300 (e2)
				 0.000 (e3)
				 0.675 (e4)
				 0.000 (e5)
				 0.025 (e6))
				(not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.316 (e2)
				 0.000 (e3)
				 0.158 (e4)
				 0.000 (e5)
				 0.526 (e6))
				(not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.243 (e2)
				 0.014 (e3)
				 0.714 (e4)
				 0.007 (e5)
				 0.021 (e6))
				(not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.310 (e2)
				 0.014 (e3)
				 0.662 (e4)
				 0.000 (e5)
				 0.014 (e6))
				(not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.625 (e2)
				 0.000 (e3)
				 0.312 (e4)
				 0.000 (e5)
				 0.062 (e6))
				(not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.267 (e2)
				 0.000 (e3)
				 0.022 (e4)
				 0.000 (e5)
				 0.711 (e6))
				(not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.017 (e1)
				 0.674 (e2)
				 0.000 (e3)
				 0.256 (e4)
				 0.000 (e5)
				 0.052 (e6))
				(not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.923 (e2)
				 0.000 (e3)
				 0.077 (e4)
				 0.000 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.893 (e2)
				 0.000 (e3)
				 0.083 (e4)
				 0.000 (e5)
				 0.024 (e6))
				(not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.675 (e2)
				 0.000 (e3)
				 0.000 (e4)
				 0.000 (e5)
				 0.325 (e6))
				(not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.218 (e2)
				 0.000 (e3)
				 0.073 (e4)
				 0.000 (e5)
				 0.709 (e6))
				(not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.491 (e2)
				 0.000 (e3)
				 0.123 (e4)
				 0.000 (e5)
				 0.386 (e6))
				(not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.997 (e2)
				 0.000 (e3)
				 0.003 (e4)
				 0.000 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.994 (e2)
				 0.000 (e3)
				 0.006 (e4)
				 0.000 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 0.959 (e2)
				 0.000 (e3)
				 0.034 (e4)
				 0.000 (e5)
				 0.007 (e6))
				(not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (e1)
				 1.000 (e2)
				 0.000 (e3)
				 0.000 (e4)
				 0.000 (e5)
				 0.000 (e6))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
(define (problem dom1) (:domain stack)
	(:objects O1 O2 O3 O4)
	(:init
		(pickloc O1) (objtype3 O1)
		(pickloc O2) (objtype3 O2)
		(pickloc O3) (objtype3 O3)
		(pickloc O4) (objtype3 O4)
		(relation1 O1 O2)
		(relation1 O1 O3)
		(relation1 O1 O4)
		(relation0 O2 O1)
		(relation1 O2 O3)
		(relation1 O2 O4)
		(relation0 O3 O1)
		(relation0 O3 O2)
		(relation1 O3 O4)
		(relation0 O4 O1)
		(relation0 O4 O2)
		(relation0 O4 O3)
		(H0)
		(S0)
	)
	(:goal (and (H3) (S4) (not (stacked)) (not (inserted))))
)
